version: '3'

services:
  arqsis:
    container_name: arqsis
    image: arqsis
    links:
    - postgres
    build:
      context: ../
      dockerfile: Arqsis/Dockerfile
    volumes:
    - .:/var/www/aspnetcoreapp
    ports:
    - 80:5000
    networks:
    - testnetwork

  postgres:
    container_name: 'postgres'
    image: postgres
    restart: always
    ports:
    - 5433:5432
    expose:
    - 5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
    - database:/var/lib/postgresql/data
    networks:
    - testnetwork

volumes:
  database:
  elastic:

networks:
  testnetwork:
    driver: bridge